name: Build And push to ECR


on:
  push:
#    pull_request:     
#        branches: ['main']
    branches: ['main']
permissions:
    contents: read
    id-token: write
jobs:
    buid_scan:
        runs-on: ubuntu-latest
        steps:
            - name: checkout the code
              uses: actions/checkout@v7
            - name: Trivy Scan 
              uses: aquasecurity/trivy-action@v0.36.0
              with:
               scan-type: 'fs'
               severity: HIGH,CRITICAL
               exit-code: 0


            - name: Build Docker Image
              run: docker build -t 871715985635.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest .
            - name: Scan Docker Image
              uses: aquasecurity/trivy-action@v0.36.0
              with:
               image-ref: 871715985635.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest
               format: table
               exit-code: 0
               ignore-unfixed: true
               severity: CRITICAL,HIGH
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                 role-to-assume: arn:aws:iam::871715985635:role/github-action-role
                 aws-region: us-east-1
            - name: Login to Amazon ECR
              id: login-ecr 
              uses: aws-actions/amazon-ecr-login@v2    
            - name: Push Docker Image to Amazon ECR
              run: docker push 871715985635.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest        
                      

 


